# Generated by Django 4.2.7 on 2025-02-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(help_text='Brief description for projects listing page', max_length=250)),
                ('description', models.JSONField(help_text='\n        Format: [\n            {"type": "heading", "content": "Overview"},\n            {"type": "text", "content": "Project description here"},\n            {"type": "heading", "content": "Challenges"},\n            {"type": "text", "content": "Challenges faced..."}\n        ]\n        ')),
                ('category', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('technologies', models.JSONField(help_text='\n        Format: [\n            {"name": "React"},\n            {"name": "Django"}\n        ]\n        ')),
                ('featured_image', models.ImageField(upload_to='projects/')),
                ('live_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('timeline', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('date_created', models.DateField()),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField(help_text='URL from devicons (e.g., https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg)')),
                ('description', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the skills grid')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
