# Generated by Django 5.1.4 on 2025-01-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='honeypot',
        ),
    ]
